### ISSUE TITLE
Make `shared_path` in `FragmentScanner` a `String`

### ISSUE THREAD

**Issue by rfairley** [overdrop/liboverdrop-rs#7]
Rather than `&str` which forces the string to be borrowed, make the `shared_path` parameter of `FragmentScanner::new()` a `String` (https://github.com/coreos/zincati/pull/43#discussion_r296730164).

**Comment by lucab** [comment]
It would probably make sense to make it a `S: Into<String>`, so that both `&str` and `String` would be accepted. (I think that would work, I didn't check)

**Comment by nabijaczleweli** [comment]
No longer applies with #20; you can pass anything that's `AsRef<Path>` as `shared_path`, and it doesn't go in an object so there aren't lifetime issues.
